version: '3'
services:
  flask:
    build: .
    container_name: flaskcookbook
    ports:
      - "5000:5000"
    environment:
      SECRET_KEY: 'you_will_never_guess'
      APP_ENV: "prod"
      APP_DEBUG: "False"
      DB_HOST: mongodb
      DB_PORT: '27017'
      DB_USER: mongodbuser
      DB_PASSWORD: your_mongodb_root_password
      IMGUR_CLIENT_ID: <imgur_client_id>

  mongodb:
    image: mongo:latest
    container_name: mongocookbook
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbuser
      MONGO_INITDB_ROOT_PASSWORD: your_mongodb_root_password
      MONGO_INITDB_DATABASE: admin
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - /db:/data/db
    ports:
      - "27016:27017"
      